### ISSUE TITLE
EditorTab cannot find Domain file

### ISSUE THREAD

**Issue by psibre** [plison/opendial#15]
It seems that over in [our talking elevator project](/EllaVator/EllaVator), the EditorTab [cannot find the Domain file](../blob/0fb643bf3db54dad7ecaa607d14a61786de42401/src/opendial/gui/EditorTab.java#L216-L218), as shown by our log output (enhanced with a stacktrace, FWIW):
```
[OpenDial] INFO: Module ModuleElla successfully attached 
[OpenDial] INFO: Module AudioModule successfully attached 
[OpenDial] INFO: Acoustic model: resource:/edu/cmu/sphinx/models/en-us/en-us 
[OpenDial] INFO: Dictionary: resource:/grammar_en/ella_en.dict 
[OpenDial] INFO: Recognition grammar: resource:/grammar_en/compact_gram.gram 
[OpenDial] SEVERE: cannot read xml file: java.io.FileNotFoundException: Domain_Opendial_Ella.xml (No such file or directory) 
java.io.FileNotFoundException: Domain_Opendial_Ella.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at opendial.gui.EditorTab.rereadFile(EditorTab.java:199)
	at opendial.gui.EditorTab.refresh(EditorTab.java:167)
	at opendial.gui.EditorTab.<init>(EditorTab.java:142)
	at opendial.gui.GUIFrame.start(GUIFrame.java:155)
	at opendial.DialogueSystem.startSystem(DialogueSystem.java:148)
	at OpenDialDemo.main(OpenDialDemo.java:33)
```
Note that everything else is working well -- the main DialogSystem *is* finding the Domain file without problems.
So this is a low-priority issue; just wanted to point it out.

**Comment by plison** [comment]
OK i see, the problem seems to be that the domain file is specified as a resource, not a file path. I think I fixed the bug now, could you please verify? Thanks!
